In [1]:
d = {"name": "혼자 공부하는 데이터 분석"}
print(d['name'])

혼자 공부하는 데이터 분석

In [2]:
import json

In [3]:
d_str = json.dumps(d, ensure_ascii= False)
print(d_str)

{"name": "혼자 공부하는 데이터 분석"}

In [4]:
print(type(d_str))

<class 'str'>

In [5]:
d2 = json.loads(d_str)
print(d2['name'])

혼자 공부하는 데이터 분석

In [6]:
print(type(d2))

<class 'dict'>

In [7]:
d3 = json.loads('{"name": "혼자 공부하는 데이터 분석", "author": "박해선", "year": 2022}')

print(d3['name'])
print(d3['author'])
print(d3['year'])

혼자 공부하는 데이터 분석
박해선
2022

In [8]:
d3 = json.loads('{"name": "혼자 공부하는 데이터 분석", "author": ["박해선", "홍길동"], "year": 2022}')

print(d3['author'][1])

홍길동

In [9]:
d4_str = """
[
    {"name": "혼자 공부하는 데이터 분석", "author": "박해선", "year": 2022},
    {"name": "혼자 공부하는 머신러닝+딥러닝", "author": "박해선", "year": 2020}
]
"""

d4 = json.loads(d4_str)
print(d4[0]['name'])

혼자 공부하는 데이터 분석

In [10]:
import pandas as pd
pd.read_json(d4_str)

/var/folders/sh/_mnj6gy531v8bk4m1yyhhth80000gn/T/ipykernel_8153/1308304786.py:2: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_json(d4_str)

               name author  year
0    혼자 공부하는 데이터 분석    박해선  2022
1  혼자 공부하는 머신러닝+딥러닝    박해선  2020

In [11]:
pd.DataFrame(d4)

               name author  year
0    혼자 공부하는 데이터 분석    박해선  2022
1  혼자 공부하는 머신러닝+딥러닝    박해선  2020

In [12]:
x_str = """
<book>
    <name>혼자 공부하는 데이터 분석</name>
    <author>박해선</author>
    <year>2022</year>
</book>
"""

In [13]:
import xml.etree.ElementTree as et
book = et.fromstring(x_str)

In [14]:
print(type(book))

<class 'xml.etree.ElementTree.Element'>

In [15]:
print(book.tag)

book

In [16]:
book_childs = list(book)
print(book_childs)

[<Element 'name' at 0x10ff60db0>, <Element 'author' at 0x10ff60e00>, <Element 'year' at 0x10ff60ea0>]

In [17]:
name, author, year = book_childs
print(name.text)
print(author.text)
print(year.text)

혼자 공부하는 데이터 분석
박해선
2022

In [18]:
name = book.findtext('name')
author = book.findtext('author')
year = book.findtext('year')

print(name)
print(author)
print(year)

혼자 공부하는 데이터 분석
박해선
2022

In [19]:
x2_str = """
<books>
    <book>
        <name>혼자 공부하는 데이터 분석</name>
        <author>박해선</author>
        <year>2022</year>
    </book>
    <book>
        <name>혼자 공부하는 머신러닝+딥러닝</name>
        <author>박해선</author>
        <year>2020</year>
    </book>
</books>
"""

In [20]:
books = et.fromstring(x2_str)
print(books.tag)

books

In [21]:
for book in books.findall('book'):
    name = book.findtext('name')
    author = book.findtext('author')
    year = book.findtext('year')

    print(name)
    print(author)
    print(year)
    print()

혼자 공부하는 데이터 분석
박해선
2022

혼자 공부하는 머신러닝+딥러닝
박해선
2020

In [22]:
pd.read_xml(x2_str)

/var/folders/sh/_mnj6gy531v8bk4m1yyhhth80000gn/T/ipykernel_8153/212699965.py:1: FutureWarning: Passing literal xml to 'read_xml' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_xml(x2_str)

               name author  year
0    혼자 공부하는 데이터 분석    박해선  2022
1  혼자 공부하는 머신러닝+딥러닝    박해선  2020